[project]
name = "py-prompthandler"
version = "2025.1"
description = "ML backend: prompt handler"
readme = "README.md"

dependencies = [
    "pydantic>=2.11",
    "jinja2>=3.1.6",
]

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "ruff>=0.1.0",
    "mypy>=1.6.0",
]

[build-system]
requires = ["setuptools >= 64.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]